### ISSUE TITLE
Publish Blurhash Kotlin (Gradle and/or Maven)

### ISSUE THREAD

**Issue by sp00ne** [woltapp/blurhash#146] opened 2021-09-17 07:32 UTC
## Description
The Kotlin implementation lacks documentation for how to install it, I'd assume you would able to import via Gradle (and/or Maven)

**Comment by vanniktech** [comment] 2022-09-12 07:08
Duplicate of #116

**Comment by Thisen** [comment] 2024-05-22 06:54
Duplicate.

**Closed by Thisen** 2024-05-22 06:54 UTC
Labels: enhancement, Kotlin
