### ISSUE TITLE
Add integration with Swift Package Manager

### ISSUE THREAD

**Issue by lukas1** [woltapp/blurhash#117] opened 2021-04-12 11:40 UTC
To enable easier integration of the library in Swift projects relying on Swift Package Manager, please add integration with Swift Package Manager.

**Comment by richardtop** [comment] 2022-03-28 22:54
Duplicate #30

**Comment by jerry-git** [comment] 2022-06-10 07:17
Duplicate of #30

**Closed by jerry-git** 2022-06-10 07:17 UTC
